<a href="https://colab.research.google.com/github/freddy-7/TI3002C/blob/main/2_Valores_Nulos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**VALORES NULOS**

In [14]:
#Cargar archivo csv desde COLAB
#from google.colab import files
#files.upload()

In [3]:
#Carga desde un archivo .csv sin indice
data = pd.read_csv('Citas_Digital_Filtrado.csv')
data.head(5)

,BDC,Fecha,Nombre Cliente,Telefono,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?,Unnamed: 15
0,Saul,NaN,Guillermo,NaN,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s...",Comenta que no se le hizo atractivo el arrenda...
1,Saul,NaN,Roberto,NaN,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso,NaN
2,Saul,NaN,Irving,NaN,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso,Se le manda msj de seguimiento 03/05/2025
3,Saul,NaN,Oswaldo,NaN,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as...",NaN
4,Saul,NaN,Rodrigo,NaN,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...,Por el detalle del carbilink compro en otra ma...

In [8]:
#Eliminar columnas innecesarias
#axis = 1 para columnas
#axis = 0 para filas
data1= data.drop(['Unnamed: 15'], axis=1)
data1

,BDC,Fecha,Nombre Cliente,Telefono,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?
0,Saul,NaN,Guillermo,NaN,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s..."
1,Saul,NaN,Roberto,NaN,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso
2,Saul,NaN,Irving,NaN,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso
3,Saul,NaN,Oswaldo,NaN,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as..."
4,Saul,NaN,Rodrigo,NaN,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,Ana,2026-07-22,Maira Escalante,NaN,Activo,0.8,1.0,1.0,0.0,Pedro Antonio,NaN,NaN,NaN,NaN,NaN
672,Ignacio,2026-07-22,Zaira Macip,NaN,Activo,0.5,0.0,0.0,0.0,Aurelio,NaN,NaN,NaN,NaN,NaN
673,Ignacio,2026-07-27,Julio Hernandez,NaN,Activo,0.5,1.0,0.0,0.0,Victor,NaN,NaN,NaN,NaN,NaN
674,Ignacio,2026-07-24,Xhunaxhi Vicente,NaN,Activo,1,1.0,1.0,1.0,Ignacio,NaN,NaN,NaN,NaN,NaN
675,Ignacio,2026-07-29,DR Jairo Rodriguez Farias,NaN,Activo,1,1.0,1.0,1.0,Victor,NaN,NaN,NaN,NaN,NaN

In [9]:
#Identificar valores nulos por columna
valores_nulos=data1.isnull().sum()
valores_nulos

BDC                                          16
Fecha                                       601
Nombre Cliente                               21
Telefono                                    674
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [10]:
#Identificar valores nulos por dataframe
valores_nulos=data1.isnull().sum().sum()
valores_nulos

np.int64(2897)

**Métodos de Sustitución de Valores Nulos**

In [38]:
#empezamos con "BDC" con ffill para llenar los valores nulos con el valor anterior, de esta manera podemos identificar los valores nulos y no perder información
data2=data1.copy()
data2["BDC "] = data2["BDC "].ffill()

In [39]:
#corroborar valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                       601
Nombre Cliente                               21
Telefono                                    674
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [40]:
#a continuación sustituiremos "Fecha" con .fillna para llenar con un valor especifico, en este caso "2030-06-19 00:00:00" ya que es un valor que no se encuentra en el dataset y no afectará a los datos, de esta manera podemos identificar los valores nulos y no perder información

data2["Fecha"] =data2["Fecha"].fillna("2030-06-19 00:00:00")

In [41]:
#corroborar valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                               21
Telefono                                    674
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [42]:
#a continuación sustituiremos "Nombre Cliente" con .fillna para llenar con un valor especifico, en este caso "Cliente no identificado" ya que es un valor que no se encuentra en el dataset y no afectará a los datos, de esta manera podemos identificar los valores nulos y no perder información
data2["Nombre Cliente "] =data2["Nombre Cliente "].fillna("Cliente no identificado")

In [43]:
#corroborar valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Telefono                                    674
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [44]:
#a continuación sustituiremos "Telefono" con .fillna para llenar con un valor especifico, en este caso "Telefono no identificado" ya que es un valor que no se encuentra en el dataset y no afectará a los datos, de esta manera podemos identificar los valores nulos y no perder información
data2["Telefono "] =data2["Telefono "].fillna("Telefono no identificado")

In [45]:
#corroborar valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Telefono                                      0
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [46]:
#luego para la columna de "Estatus de Lead" vamos a sustituir los valores nulos con "Estatus no identificado" ya que es un valor que no se encuentra en el dataset y no afectará a los datos, de esta manera podemos identificar los valores nulos y no perder información
data2["Estatus de Lead"] =data2["Estatus de Lead"].fillna("Estatus no identificado")

In [47]:
#corroborar valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Telefono                                      0
Estatus de Lead                               0
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [ ]:
#convertimos la columande Potencial de compra a tipo float para poder hacer operaciones matematicas con ella, primero eliminamos los caracteres que no son numeros y luego convertimos a float
data2['Potencial de compra'].unique

data2['Potencial de compra']=data2['Potencial de compra'].astype("string")
data2['Potencial de compra']=data2['Potencial de compra'].str.replace("Ventas ","0", regex=False)
data2['Potencial de compra']=data2['Potencial de compra'].str.replace("%","", regex=False)
data2['Potencial de compra']=data2['Potencial de compra'].str.replace("'","", regex=False)
data2['Potencial de compra']=data2['Potencial de compra'].str.replace("&","", regex=False)

data2['Potencial de compra']=data2['Potencial de compra'].astype(float)

In [52]:
#seguimos con "Potencial de compra" con la mediana para llenar los valores nulos con el valor de la mediana, de esta manera podemos identificar los valores nulos y no perder información
data2["Potencial de compra"] = data2["Potencial de compra"].fillna(round(data2["Potencial de compra"].median(),1))

In [53]:
#corroborar valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Telefono                                      0
Estatus de Lead                               0
Potencial de compra                           0
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [54]:
#a continuación vamos a sustituir "Venta" con .fillna para llenar con un valor especifico, en este caso "2" ya que es un valor que no se encuentra en el dataset y no afectará a los datos, de esta manera podemos identificar los valores nulos y no perder información
data2["Venta"] =data2["Venta"].fillna("2")

In [55]:
#corroborar valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Telefono                                      0
Estatus de Lead                               0
Potencial de compra                           0
PDM                                           1
SDC                                           2
Venta                                         0
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [56]:
#para "asesor asignado" vamos a sustituir los valores nulos con "Asesor no identificado" ya que es un valor que no se encuentra en el dataset y no afectará a los datos, de esta manera podemos identificar los valores nulos y no perder información
data2["Asesor Asignado"] =data2["Asesor Asignado"].fillna("Asesor no identificado")

In [57]:
#corroborar valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Telefono                                      0
Estatus de Lead                               0
Potencial de compra                           0
PDM                                           1
SDC                                           2
Venta                                         0
Asesor Asignado                               0
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [59]:
#para las preguntas despues de asesor asignado, utlizaremos el método fillna con el valor "No hay información" ya que es un valor que no se encuentra en el dataset y no afectará a los datos, de esta manera podemos identificar los valores nulos y no perder información
data2[["¿Por que no ha visitado la agencia?","¿Por que no hay solicitud de credito?","¿Por que no hubo prueba de manejo ?","¿Por que no hubo proceso wow?","¿Por que se asigno antes de vistar piso?"]] =data2[["¿Por que no ha visitado la agencia?","¿Por que no hay solicitud de credito?","¿Por que no hubo prueba de manejo ?","¿Por que no hubo proceso wow?","¿Por que se asigno antes de vistar piso?"]].fillna("No hay información")

In [60]:
#corroborar valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

BDC                                         0
Fecha                                       0
Nombre Cliente                              0
Telefono                                    0
Estatus de Lead                             0
Potencial de compra                         0
PDM                                         1
SDC                                         2
Venta                                       0
Asesor Asignado                             0
¿Por que no ha visitado la agencia?         0
¿Por que no hay solicitud de credito?       0
¿Por que no hubo prueba de manejo ?         0
¿Por que no hubo proceso wow?               0
¿Por que se asigno antes de vistar piso?    0
dtype: int64

**Método de Eliminación de valores nulos**

In [70]:
#Identificar valores nulos por columna
valores_nulos=data1.isnull().sum()
valores_nulos

BDC                                          16
Fecha                                       601
Nombre Cliente                               21
Telefono                                    674
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [71]:
#Eliminamos filas con nulos
#No se agrega nada para eliminar filas y 1 para eliminar columnas
data3 = data2.dropna(subset=["PDM", "SDC"])

In [72]:
#corroborar valores nulos
valores_nulos=data3.isnull().sum()
valores_nulos

BDC                                         0
Fecha                                       0
Nombre Cliente                              0
Telefono                                    0
Estatus de Lead                             0
Potencial de compra                         0
PDM                                         0
SDC                                         0
Venta                                       0
Asesor Asignado                             0
¿Por que no ha visitado la agencia?         0
¿Por que no hay solicitud de credito?       0
¿Por que no hubo prueba de manejo ?         0
¿Por que no hubo proceso wow?               0
¿Por que se asigno antes de vistar piso?    0
dtype: int64

**Comparamos DataFrame3(Sustitución) y Dataframe4(Eliminación)**

In [73]:
data2.info()

<class 'pandas.DataFrame'>
RangeIndex: 676 entries, 0 to 675
Data columns (total 15 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   BDC                                       676 non-null    str
 1   Fecha                                     676 non-null    str
 2   Nombre Cliente                            676 non-null    str
 3   Telefono                                  676 non-null    str
 4   Estatus de Lead                           676 non-null    str
 5   Potencial de compra                       676 non-null    float64
 6   PDM                                       675 non-null    float64
 7   SDC                                       674 non-null    float64
 8   Venta                                     676 non-null    object
 9   Asesor Asignado                           676 non-null    str
 10  ¿Por que no ha visitado la agencia?       676 non-null    str
 11  ¿Por que no hay solicitud de credito?     676 non-null    str
 12  ¿Por que no hubo prueba de manejo ?       676 non-null    str
 13  ¿Por que no hubo proceso wow?             676 non-null    str
 14  ¿Por que se asigno antes de vistar piso?  676 non-null    str
dtypes: float64(3), object(1), str(11)
memory usage: 79.3+ KB

In [74]:
data3.info()

<class 'pandas.DataFrame'>
Index: 674 entries, 0 to 675
Data columns (total 15 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   BDC                                       674 non-null    str
 1   Fecha                                     674 non-null    str
 2   Nombre Cliente                            674 non-null    str
 3   Telefono                                  674 non-null    str
 4   Estatus de Lead                           674 non-null    str
 5   Potencial de compra                       674 non-null    float64
 6   PDM                                       674 non-null    float64
 7   SDC                                       674 non-null    float64
 8   Venta                                     674 non-null    object
 9   Asesor Asignado                           674 non-null    str
 10  ¿Por que no ha visitado la agencia?       674 non-null    str
 11  ¿Por que no hay solicitud de credito?     674 non-null    str
 12  ¿Por que no hubo prueba de manejo ?       674 non-null    str
 13  ¿Por que no hubo proceso wow?             674 non-null    str
 14  ¿Por que se asigno antes de vistar piso?  674 non-null    str
dtypes: float64(3), object(1), str(11)
memory usage: 84.2+ KB

**Convertir DataSet sin valores nulos a CSV**

In [75]:
#Convertir DataFrame a CSV
data3.to_csv("Citas_Digital_Sin_Nulos.csv", index=False)

In [ ]:
#descargar archivo filtrado en csv
#from google.colab import files 
  
  
#files.download("inmuebles_sin_nulos.csv")