<a href="https://colab.research.google.com/github/freddy-7/TI3002C/blob/main/2_Valores_Nulos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**VALORES NULOS**

In [14]:
#Cargar archivo csv desde COLAB
#from google.colab import files
#files.upload()

In [2]:
#Carga desde un archivo .xlsx sin indice
data = pd.read_excel('Análisis_de_Piso.xlsx')
data.head(5)

,Unnamed: 0,Leads Piso 2024,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Ventas Piso 2025,Unnamed: 33,Unnamed: 34,Unnamed: 35,* se actualiza al reportar en Sale-U
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Asesor,feb,mar,abr,may,jun,jul,ago,sep,oct,...,sep,oct,nov,dic,ene,feb,mar,abr,May,Junio
2,ABIGAIL,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
3,ALAN GONZALES,1,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,...,NaN,NaN,1,2,4,1,2,1,1,NaN
4,ALICIA LEDESMA,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN

In [ ]:
#borre las primeras dos filas del archivo porque no tenían información relevante, esto para evitar nulos no relevantes en el análisis
data1= pd.read_excel('Análisis_de_Piso.xlsx', skiprows=2)
data1

,Asesor,feb,mar,abr,may,jun,jul,ago,sep,oct,...,sep.1,oct.1,nov.1,dic.1,ene.1,feb.3,mar.3,abr.3,May,Junio
0,ABIGAIL,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
1,ALAN GONZALES,1.0,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,...,NaN,NaN,1.0,2.0,4.0,1.0,2.0,1,1.0,NaN
2,ALICIA LEDESMA,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
3,AURELIO FELIPE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,6.0,...,NaN,2.0,NaN,NaN,NaN,NaN,1.0,,3.0,2.0
4,CARLOS ALBERTO NIETO,NaN,NaN,NaN,2.0,NaN,NaN,2.0,8,4.0,...,2.0,NaN,3.0,1.0,NaN,3.0,NaN,,NaN,NaN
5,CARLOS TEXIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,,NaN,NaN
6,CARLOS MANUEL CARMONA,18.0,10.0,27.0,34.0,11.0,3.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
7,CINTYA,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
8,CLAUDIA GALVAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
9,CASA,1.0,NaN,3.0,3.0,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,1.0,NaN,,NaN,NaN
10,DANIEL DE LEON CANDIA,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1,5.0,...,NaN,NaN,1.0,1.0,1.0,2.0,NaN,,NaN,NaN
11,DAVID JIMENEZ,NaN,NaN,10.0,5.0,7.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
12,Demo Vendedor,2.0,2.0,2.0,NaN,NaN,3.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
13,GUADALUPE PEREZ,NaN,NaN,1.0,2.0,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
14,SEBASTIAN BENHUMEA,1.0,NaN,1.0,NaN,NaN,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
15,USUARIO DE BDC Y CASA,2.0,1.0,4.0,1.0,NaN,3.0,6.0,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
16,JAIME GONZALEZ,NaN,NaN,1.0,1.0,4.0,12.0,29.0,8,7.0,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
17,JESUS SERRANO,114.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
18,JOSE CARLOS ZENTENO,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
19,JOSE EDUARDO PARADA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
20,JOSE MANUEL LOPEZ,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
21,JOSE MANUEL LOPEZ,67.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
22,JOSETTE RAMON,NaN,NaN,NaN,2.0,5.0,17.0,5.0,9,NaN,...,1.0,NaN,3.0,NaN,NaN,NaN,NaN,,NaN,NaN
23,LAURA LOPEZ,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
24,LIZBETH GOMEZ GONZALEZ,10.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
25,LUIS ALBERTO RODRIGUEZ,6.0,NaN,12.0,NaN,NaN,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
26,LUISA LBERTO GOMEZ,42.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
27,MARIA GUADALUPE PALACIOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,1.0,NaN,NaN,,NaN,NaN
28,MAURICIO ALFREDO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2,2.0,1.0
29,MIGUEL ANGEL SONDEREGGER,37.0,NaN,4.0,36.0,21.0,37.0,25.0,16,8.0,...,1.0,NaN,2.0,1.0,1.0,NaN,NaN,,NaN,NaN
30,MONICA GISELA FLORES,NaN,NaN,NaN,NaN,NaN,2.0,7.0,5,2.0,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
31,NANCY OLASCOAGA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
32,NAYELI MONTES DEOCA,41.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
33,OSCAR ALONSO,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
34,PAUL ROSAS IRIGOYIN,1.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
35,PAUL ROSAS,83.0,7.0,11.0,6.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
36,PEDRO GONZALES,2.0,NaN,11.0,17.0,7.0,19.0,11.0,5,2.0,...,1.0,NaN,NaN,1.0,3.0,3.0,2.0,1,2.0,NaN
37,RICARDO SILVA HERAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1.0,NaN
38,sys_competition,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN
39,VICTOR MANUEL SANCHEZ ARROYO,4.0,3.0,NaN,1.0,2.0,NaN,NaN,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,,3.0,NaN
40,NaN,459.0,27.0,95.0,110.0,65.0,107.0,88.0,59,40.0,...,6.0,3.0,11.0,8.0,10.0,12.0,9.0,4,12.0,3.0

In [4]:
#Identificar valores nulos por columna
valores_nulos=data1.isnull().sum()
valores_nulos

Asesor          1
feb            19
mar            31
abr            23
may            28
jun            30
jul            29
ago            30
sep            27
oct            31
nov            25
dic            31
ene            30
feb.1          30
mar.1          33
abr.1          31
                0
 .1             0
Unnamed: 18     1
Unnamed: 19     1
feb.2           0
mar.2          38
abr.2          35
may.1          39
jun.1          38
jul.1          36
ago.1          36
sep.1          35
oct.1          38
nov.1          34
dic.1          34
ene.1          35
feb.3          33
mar.3          35
abr.3           0
May            34
Junio          38
dtype: int64

In [5]:
#Identificar valores nulos por dataframe
valores_nulos=data1.isnull().sum().sum()
valores_nulos

np.int64(969)

**Métodos de Sustitución de Valores Nulos**

In [ ]:
#a continuación sustituiremos "asesor" con .fillna para llenar con un valor especifico, en este caso "Asesor no identificado" ya que es un valor que no se encuentra en el dataset y no afectará a los datos, de esta manera podemos identificar los valores nulos y no perder información

data1["Asesor "] =data1["Asesor "].fillna("Asesor no identificado")

In [8]:
#corroborar valores nulos
valores_nulos=data1.isnull().sum()
valores_nulos

Asesor          0
feb            19
mar            31
abr            23
may            28
jun            30
jul            29
ago            30
sep            27
oct            31
nov            25
dic            31
ene            30
feb.1          30
mar.1          33
abr.1          31
                0
 .1             0
Unnamed: 18     1
Unnamed: 19     1
feb.2           0
mar.2          38
abr.2          35
may.1          39
jun.1          38
jul.1          36
ago.1          36
sep.1          35
oct.1          38
nov.1          34
dic.1          34
ene.1          35
feb.3          33
mar.3          35
abr.3           0
May            34
Junio          38
dtype: int64

In [ ]:
a continuación sustituimos los valores nulos de las columnas de meses con .fillna para llenar con un valor especifico, en este caso "0" ya que no representa ninguna venta para los asesores que previamente limpiamos
data1[["feb","mar","abr","may","jun","jul","ago","sep","oct","nov","dic","ene","feb.1","mar.1","abr.1"]] =data1[["feb","mar","abr","may","jun","jul","ago","sep","oct","nov","dic","ene","feb.1","mar.1","abr.1"]].fillna("0")

In [10]:
#corroborar valores nulos
valores_nulos=data1.isnull().sum()
valores_nulos

Asesor          0
feb             0
mar             0
abr             0
may             0
jun             0
jul             0
ago             0
sep             0
oct             0
nov             0
dic             0
ene             0
feb.1           0
mar.1           0
abr.1           0
                0
 .1             0
Unnamed: 18     1
Unnamed: 19     1
feb.2           0
mar.2          38
abr.2          35
may.1          39
jun.1          38
jul.1          36
ago.1          36
sep.1          35
oct.1          38
nov.1          34
dic.1          34
ene.1          35
feb.3          33
mar.3          35
abr.3           0
May            34
Junio          38
dtype: int64

In [ ]:
#repetimos los mismos pasos para las columnas de meses que se encuentran al final del dataset, ya que también contienen valores nulos, sustituyendo con 0
data1[["Unnamed: 18","Unnamed: 19","mar.2","abr.2","may.1","jun.1","jul.1","ago.1","sep.1","oct.1","nov.1","dic.1","ene.1","feb.3","mar.3","May ","Junio"]] =data1[["Unnamed: 18","Unnamed: 19","mar.2","abr.2","may.1","jun.1","jul.1","ago.1","sep.1","oct.1","nov.1","dic.1","ene.1","feb.3","mar.3","May ","Junio"]].fillna("0")

In [14]:
#corroborar valores nulos
valores_nulos=data1.isnull().sum()
valores_nulos

Asesor         0
feb            0
mar            0
abr            0
may            0
jun            0
jul            0
ago            0
sep            0
oct            0
nov            0
dic            0
ene            0
feb.1          0
mar.1          0
abr.1          0
               0
 .1            0
Unnamed: 18    0
Unnamed: 19    0
feb.2          0
mar.2          0
abr.2          0
may.1          0
jun.1          0
jul.1          0
ago.1          0
sep.1          0
oct.1          0
nov.1          0
dic.1          0
ene.1          0
feb.3          0
mar.3          0
abr.3          0
May            0
Junio          0
dtype: int64

**Comparamos DataFrame3(Sustitución) y Dataframe4(Eliminación)**

In [16]:
data1.info()

<class 'pandas.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 37 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Asesor       41 non-null     str
 1   feb          41 non-null     object
 2   mar          41 non-null     object
 3   abr          41 non-null     object
 4   may          41 non-null     object
 5   jun          41 non-null     object
 6   jul          41 non-null     object
 7   ago          41 non-null     object
 8   sep          41 non-null     object
 9   oct          41 non-null     object
 10  nov          41 non-null     object
 11  dic          41 non-null     object
 12  ene          41 non-null     object
 13  feb.1        41 non-null     object
 14  mar.1        41 non-null     object
 15  abr.1        41 non-null     object
 16               41 non-null     int64
 17   .1          41 non-null     int64
 18  Unnamed: 18  41 non-null     object
 19  Unnamed: 19  41 non-null     object
 20  feb.2        41 non-null     object
 21  mar.2        41 non-null     object
 22  abr.2        41 non-null     object
 23  may.1        41 non-null     object
 24  jun.1        41 non-null     object
 25  jul.1        41 non-null     object
 26  ago.1        41 non-null     object
 27  sep.1        41 non-null     object
 28  oct.1        41 non-null     object
 29  nov.1        41 non-null     object
 30  dic.1        41 non-null     object
 31  ene.1        41 non-null     object
 32  feb.3        41 non-null     object
 33  mar.3        41 non-null     object
 34  abr.3        41 non-null     object
 35  May          41 non-null     object
 36  Junio        41 non-null     object
dtypes: int64(2), object(34), str(1)
memory usage: 12.0+ KB

**Convertir DataSet sin valores nulos a CSV**

In [17]:
#Convertir DataFrame a CSV
data1.to_csv("Análisis_de_Piso_Sin_Nulos.csv", index=False)

In [ ]:
#descargar archivo filtrado en csv
#from google.colab import files 
  
  
#files.download("inmuebles_sin_nulos.csv")