<a href="https://colab.research.google.com/github/freddy-7/TI3002C/blob/main/2_Valores_Nulos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**VALORES NULOS**

In [14]:
#Cargar archivo csv desde COLAB
#from google.colab import files
#files.upload()

In [8]:
#Carga desde un archivo .xlsx sin indice
data = pd.read_excel('Base_de_Tlaxcala.xlsx')
data.head(5)

,Fecha de Alta,Mes Lead,AgLead,Titulo,Nombre,Telefono,Correo,Producto,Temperatura,Comentario,Asesor,Fuente,Origen,Estatus
0,2025-10-30,10,560dd80fc9a1878495e1af33f7b4bd95,Lead GALERIAS TLAXCALA,Jose Juan Felipe Arenas Huerta,NaN,NaN,EMZOOM,Lead Interes Bajo,Cita en Custom-Prueba de manejoFinal:EMZOOM,Antonio Licona,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Contactado
1,2025-10-28,10,98a6be793540ff2fd5d29f4c4d1db313,Lead GALERIAS TLAXCALA,Guillermo Ortiz Lopez,NaN,NaN,EMZOOM,Lead Interes Medio,quiere cotizaciÃ³n de arrendamiento y financia...,Alvaro Celso Mora Rosete,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Contactado
2,2025-10-27,10,6704bccc5cddec9bc40d0cc1962b13c9,Lead GALERIAS TLAXCALA,Mireya De Lucio,NaN,NaN,EMZOOM,Lead Interes Medio,mandar cotizacioneaPidieron:GS4 MAX GL,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Contactado
3,2025-10-27,10,1c4b5a464d33036f8f3848eba6b4946f,Lead GALERIAS TLAXCALA,Francisco Javier Flores Caldera,NaN,NaN,EMZOOM,Lead Interes Medio,quiere que le mande ficha tÃ©cnica catÃ¡logo y...,Alvaro Celso Mora Rosete,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Contactado
4,2025-10-23,10,7cf8d8cb36bef73fd710a82e0e585a1c,Lead GALERIAS TLAXCALA,Sarahi Mendieta,NaN,NaN,EMZOOM,Lead Interes Medio,Se programa para el sabado una prueba de manej...,Antonio Licona,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado

In [12]:
#Eliminar columnas innecesarias
#axis = 1 para columnas
#axis = 0 para filas
data1= data.drop(['Correo','Telefono'], axis=1)
data1

,Fecha de Alta,Mes Lead,AgLead,Titulo,Nombre,Producto,Temperatura,Comentario,Asesor,Fuente,Origen,Estatus
0,2025-10-30,10,560dd80fc9a1878495e1af33f7b4bd95,Lead GALERIAS TLAXCALA,Jose Juan Felipe Arenas Huerta,EMZOOM,Lead Interes Bajo,Cita en Custom-Prueba de manejoFinal:EMZOOM,Antonio Licona,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Contactado
1,2025-10-28,10,98a6be793540ff2fd5d29f4c4d1db313,Lead GALERIAS TLAXCALA,Guillermo Ortiz Lopez,EMZOOM,Lead Interes Medio,quiere cotizaciÃ³n de arrendamiento y financia...,Alvaro Celso Mora Rosete,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Contactado
2,2025-10-27,10,6704bccc5cddec9bc40d0cc1962b13c9,Lead GALERIAS TLAXCALA,Mireya De Lucio,EMZOOM,Lead Interes Medio,mandar cotizacioneaPidieron:GS4 MAX GL,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Contactado
3,2025-10-27,10,1c4b5a464d33036f8f3848eba6b4946f,Lead GALERIAS TLAXCALA,Francisco Javier Flores Caldera,EMZOOM,Lead Interes Medio,quiere que le mande ficha tÃ©cnica catÃ¡logo y...,Alvaro Celso Mora Rosete,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Contactado
4,2025-10-23,10,7cf8d8cb36bef73fd710a82e0e585a1c,Lead GALERIAS TLAXCALA,Sarahi Mendieta,EMZOOM,Lead Interes Medio,Se programa para el sabado una prueba de manej...,Antonio Licona,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
5,2025-10-22,10,9ea326ab1c361795b86fa2d6525e1275,Lead GALERIAS TLAXCALA,Elias Mendez De Gante,EMZOOM,Lead Interes Medio,se manda informes Pidieron:GS4 MAX HEV,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
6,2025-10-21,10,963fdac02b41856f6d3f8974c87c15b9,Lead GALERIAS TLAXCALA,Lauro Sanchez,GS8,Lead Interes Medio,se manda informesPidieron:GS8,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
7,2025-10-20,10,2df51d10624eef47a6faee6c2f7de0ac,Lead GALERIAS TLAXCALA,Alberto Corona,EMZOOM,Lead Interes Medio,mandar catalogoPidieron:GS4 MAX GL,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
8,2025-10-20,10,7ed793a1c033a95ef72b5162351d794f,Lead GALERIAS TLAXCALA,Hilario Romero,EMKOO,Lead Interes Medio,mandar catalogoPidieron:EMKOO,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
9,2025-10-20,10,173961258beb7c8175f27101948ecce2,Lead GALERIAS TLAXCALA,David Eduardo Meneses Manzano,EMZOOM,Lead Muy Interesado,se manda whats con informes y se somete solici...,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,1 Ventas
10,2025-10-19,10,026a96e3e32b488909803eeadffa8928,Lead GALERIAS TLAXCALA,Elizabeth E,EMZOOM,Lead Interes Medio,hibridaPidieron:GS4 MAX,VICTOR MANUEL SANCHEZ ARROYO,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Contactado
11,2025-10-19,10,76a5b7ea3699545acee6924609aa750c,Lead GALERIAS TLAXCALA,Demetrio Morales,EMKOO,Lead Interes Medio,glFinal:EMKOO,VICTOR MANUEL SANCHEZ ARROYO,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
12,2025-10-17,10,ad5ae3d3739a9522ad84dbf8f8f0489a,Lead GALERIAS TLAXCALA,Alonso Jahel Vargas,EMZOOM,Lead Interes Medio,mandar informes con 48 meses y 20 % enganchePi...,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
13,2025-10-17,10,0787d217108bb0bd09cfd2de214981a6,Lead GALERIAS TLAXCALA,Cesar Castanuelas,GS8,Lead Interes Medio,mandar informes de gs8 con 30 % enganche a 48 ...,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
14,2025-10-17,10,bc6f645764f3bfd0d7053fa32e53c836,Lead GALERIAS TLAXCALA,Maria Elia Barios Juarez,GS8,Lead Interes Medio,mandar cotizaciones con 50 % de enganche a 60 ...,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
15,2025-10-17,10,6626d81d56fd996c697cdc6eb74783e6,Lead GALERIAS TLAXCALA,Diego Mendieta,EMZOOM,Lead Interes Medio,GS4 glPidieron:EMZOOM,VICTOR MANUEL SANCHEZ ARROYO,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
16,2025-10-17,10,53131a592eb40dafeda86c13baafd021,Lead GALERIAS TLAXCALA,Alberto Duran,EMZOOM,Lead Interes Medio,GS4 glPidieron:EMZOOM,VICTOR MANUEL SANCHEZ ARROYO,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Contactado
17,2025-10-16,10,7e781ca1309b21462277881797106875,Lead GALERIAS TLAXCALA,Yasmin Bonilla,EMKOO,Lead Interes Medio,PidiÃ³ informaciÃ³n y la ubicaciÃ³n de la agen...,Jhoslaan Torres Ramirez,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
18,2025-10-15,10,05bcddbca7412a6822c0190eb8af74f8,Lead GALERIAS TLAXCALA,Maria Celestes,EMKOO,Lead Interes Medio,Solicito informaciÃ³n Pidieron:EMKOO HEV,Jhoslaan Torres Ramirez,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Contactado
19,2025-10-15,10,73cd061c58579e515637e6fdaf3ea9fc,Lead GALERIAS TLAXCALA - Return,Fernando Gutierrez,NaN,Lead Interes Medio,Solo pidi? in,PEDRO ANTONIO CINTO DE GANTE,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
20,2025-10-15,10,8148a25efae63eca776ea98c8c8e0e74,Lead GALERIAS TLAXCALA,Carlos Tlapale,EMZOOM,Lead Interes Medio,Se programa una cita para el Pidieron:EMZOOM,Jhoslaan Torres Ramirez,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Contactado
21,2025-10-15,10,f59c813076e034fde5941bccf74e75fe,Lead GALERIAS TLAXCALA,Hugo Melendez,EMZOOM,Lead Interes Medio,racerPidieron:EMZOOM,VICTOR MANUEL SANCHEZ ARROYO,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
22,2025-10-15,10,2a1e40374ad7f822147e1a7c07a246dc,Lead GALERIAS TLAXCALA,Mari Carmen Lein,GS8,Lead Interes Medio,se manda informes llamar y aclarar dudasPidi...,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Contactado
23,2025-10-15,10,3b38cb4c93d73c05fb07f16d2cb7507d,Lead GALERIAS TLAXCALA,Fernando Paredes Lara,GS8,Lead Interes Medio,se manda whats para agendar citaPidieron:GS8,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
24,2025-10-15,10,edc9dbb2b6bd5618e6f22416bbf59a09,Lead GALERIAS TLAXCALA,Miriam Monserrat Montes Temolzin,EMZOOM,Lead Interes Medio,quiere ver la unidadPidieron:EMZOOM,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
25,2025-10-14,10,d12faa6982592891b715209fbf754c09,Lead GALERIAS TLAXCALA,Elvia Mendoza Cano,EMZOOM,Lead Interes Medio,mandar cotizaciones de emzoom con 30% a 24 y 4...,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Contactado
26,2025-10-14,10,d4578a5a4e2013ff6c473191cc737fb2,Lead GALERIAS TLAXCALA,Gabriel Portillo Manzano,GS8,Lead Interes Medio,mandar cotizaciones con 20% enganche y 60 mese...,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
27,2025-10-13,10,b9bc5a8a028b3ffd3aef70a39e66ce2a,Lead GALERIAS TLAXCALA,Jose Angel Hernandez,GS8,Lead Interes Medio,mandar cotizaciones a 1 y 2 aÃ±os con 50% de e...,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
28,2025-10-13,10,7517294f0e7b3e9b6ee891c05b11406b,Lead GALERIAS TLAXCALA,Spenser Castro,GS8,Lead Interes Medio,mandar cotizaciones con 40 % enganche y 60 mes...,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Contactado
29,2025-10-13,10,c9a691d50116111e1914492bcb7c887a,Lead GALERIAS TLAXCALA,Francisco Javier Rodriguez Lima,GS8,Lead Interes Medio,mandar cotizaciones 250 enganche 48 mesesPidie...,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
30,2025-10-13,10,cb815f7a4a6f81686e7d8a085f0f29b5,Lead GALERIAS TLAXCALA,Angelica Espino,GS8,Lead Interes Medio,manda ficha y preciosPidieron:GS8,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Contactado
31,2025-10-11,10,ad74e54cff9f1b9140f66c97dbcc6e1d,Lead GALERIAS TLAXCALA,Ing Arturo Flores,EMZOOM,Lead Interes Medio,racerPidieron:EMZOOM,VICTOR MANUEL SANCHEZ ARROYO,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
32,2025-10-11,10,36b5c98a4b805f056279f5cf608422d4,Lead GALERIAS TLAXCALA,Daniel D,GS8,Lead Interes Medio,gt fwdPidieron:GS8,VICTOR MANUEL SANCHEZ ARROYO,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
33,2025-10-11,10,d21105e1d811d904181893a4671dc30b,Lead GALERIAS TLAXCALA,Jose Angel Martinez,GS8,Lead Interes Medio,gt fwdPidieron:GS8,VICTOR MANUEL SANCHEZ ARROYO,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
34,2025-10-10,10,8ce58567f784c80ac22d048fb3c8ded3,Lead GALERIAS TLAXCALA,Elydde Alcala Perez,EMZOOM,Lead Muy Interesado,ApartadoPidieron:EMZOOM,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,1 Ventas
35,2025-10-10,10,ce9f6b341d09a59fa1886cb42f8bb7f2,Lead GALERIAS TLAXCALA,Jorge Rodriguez,GS8,Lead Interes Medio,gtPidieron:GS8,VICTOR MANUEL SANCHEZ ARROYO,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
36,2025-10-10,10,b07d050b1daaa06a4ccdb6c13f9821dc,Lead GALERIAS TLAXCALA,Mendieta Cuapio,GS8,Lead Interes Medio,solicito ficha tÃ©cnica Pidieron:GS8,VICTOR MANUEL SANCHEZ ARROYO,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
37,2025-10-09,10,6cc15bc1ab34e24a99f78c50df92ec1e,Lead GALERIAS TLAXCALA,Glooria Linda,EMZOOM,Lead Interes Medio,contactarPidieron:EMZOOM,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
38,2025-10-09,10,3644fcb115f4b6acb8acff6c4d94f513,Lead GALERIAS TLAXCALA,Rodrigo Hernandez,EMZOOM,Lead Interes Medio,Quedo en visitarnos pero no contesta las llama...,Jhoslaan Torres Ramirez,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Contactado
39,2025-10-09,10,fe9cf68c02eff2ca163f302c3deb466c,Lead GALERIAS TLAXCALA,Ana Suarez,EMZOOM,Lead Interes Medio,Sele mando ficha tÃ©cnica no responde mensaje...,Jhoslaan Torres Ramirez,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Contactado
40,2025-10-09,10,897b38461d2d867295568b246888946e,Lead GALERIAS TLAXCALA,Angel Estrada Perez,EMZOOM,Lead Interes Medio,PidiÃ³ marcarle la siguiente Samanta Pidieron:...,Jhoslaan Torres Ramirez,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Contactado
41,2025-10-09,10,fcb17d21ff43f38fc09a0d6e06b0c895,Lead GALERIAS TLAXCALA,Jorge Briseno,EMKOO,Lead Interes Medio,PidiÃ³ informaciÃ³n para fin de aÃ±o esta inte...,Jhoslaan Torres Ramirez,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
42,2025-10-09,10,b34ac9ec69ab060fe4b34bfb3f688f16,Lead GALERIAS TLAXCALA,Juan Carlos Salamanca,GS8,Lead Interes Medio,GS8 30% enganche 60 mesesPidieron:GS8,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
43,2025-10-07,10,9c63b1941b8ede9abe3e19a38231b58e,Lead GALERIAS TLAXCALA,Emmanuel Portillo,GS8,Lead Interes Medio,mandar cotizaciones con 50% a 24 meses GS8 GTP...,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
44,2025-10-07,10,77e37a76917974700e7fa0493037cdb8,Lead GALERIAS TLAXCALA,Romulo Rives,GS8,Lead Interes Medio,mandar cotizaciones. con 20% y 60 meses de GS8...,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
45,2025-10-05,10,853ca0a4973724e226c95a8a86d6c93c,Lead GALERIAS TLAXCALA,Elizabeth Perez De La Cruz,EMZOOM,Lead Interes Medio,llevar unidad a santa ana gs4 hibridaPidieron:...,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
46,2025-10-05,10,c362ce9f7be9f5adf86bf62e60b9c114,Lead GALERIAS TLAXCALA,Jose Heriberto Castilla,GS8,Lead Interes Medio,mandar informes de GS8 con 20% de enganche a 6...,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Contactado
47,2025-10-04,10,97f8e8c38c1904e9de288ac95db988e0,Lead GALERIAS TLAXCALA,Jose Angel Cruz Garcia,GS8,Lead Interes Medio,mandar informes con 400 mil a 48 meses y 60 Pi...,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
48,2025-10-04,10,dac6a75252a02330f5be26b501712bd4,Lead GALERIAS TLAXCALA,Javier Sastre,EMKOO,Lead Interes Medio,mandar informes con 30% enganche y 60 m3esesPi...,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
49,2025-10-03,10,89773c0df8243c62bbd325a37cc30daa,Lead GALERIAS TLAXCALA,Manuel Capistran,EMZOOM,Lead Interes Medio,se manda whatsPidieron:EMZOOM,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
50,2025-10-02,10,ffeb4cf64bdfa16d406ee8a25208dbc3,Lead GALERIAS TLAXCALA,Jaime Melendez,EMKOO,Lead Interes Medio,gasolinaPidieron:EMKOO,VICTOR MANUEL SANCHEZ ARROYO,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
51,2025-10-01,10,262e2fdbec9b69aefbed4bec77bcd386,Lead GALERIAS TLAXCALA,Salvador Quintero,EMKOO,Lead Interes Medio,mandar informes de emkooPidieron:EMKOO,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Contactado
52,2025-10-01,10,4eff8f613221bc5be85c96b349025eaa,Lead GALERIAS TLAXCALA,Manuel Roldan,EMKOO,Lead Interes Bajo,Compra en el fin de mes Pidieron:EMKOO,Jhoslaan Torres Ramirez,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Contactado
53,2025-10-01,10,7d76416e37e7896c9326f1043dc8ea9c,Lead GALERIAS TLAXCALA,Manuel Salauz,EMZOOM,Lead Interes Medio,Marcar el fin de semana para agendar cita y pr...,Jhoslaan Torres Ramirez,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Contactado
54,2025-10-01,10,b1af8be51d8f8ade69141b61546d7c9e,Lead GALERIAS TLAXCALA,Ximena Atonal,EMZOOM,Lead Interes Medio,mandar promos 24 meses sin interesesPidieron:E...,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado
55,2025-10-01,10,888a8592e10bb4b99c5289fd6e348611,Lead GALERIAS TLAXCALA,Edgar Alvarez Diaz,EMZOOM,Lead Interes Medio,mandar cotizaciones es a 24 meses sin interese...,JULIO CESAR GARCIA GARCIA,11.Origen Personalizado/Calle,GALERIAS TLAXCALA,Finalizado

In [13]:
#corroborar valores nulos
valores_nulos=data1.isnull().sum()
valores_nulos

Fecha de Alta    0
Mes Lead         0
AgLead           0
Titulo           0
Nombre           0
Producto         1
Temperatura      0
Comentario       0
Asesor           0
Fuente           0
Origen           0
Estatus          0
dtype: int64

In [14]:
#Identificar valores nulos por dataframe
valores_nulos=data1.isnull().sum().sum()
valores_nulos

np.int64(1)

**Métodos de Sustitución de Valores Nulos**

In [15]:
#empezamos con "BDC" con ffill para llenar los valores nulos con el valor anterior, de esta manera podemos identificar los valores nulos y no perder información
data2=data1.copy()
data2["Producto"] = data2["Producto"].ffill()

In [16]:
#corroborar valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

Fecha de Alta    0
Mes Lead         0
AgLead           0
Titulo           0
Nombre           0
Producto         0
Temperatura      0
Comentario       0
Asesor           0
Fuente           0
Origen           0
Estatus          0
dtype: int64

**Comparamos DataFrame3(Sustitución) y Dataframe4(Eliminación)**

In [17]:
data2.info()

<class 'pandas.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Fecha de Alta  56 non-null     datetime64[us]
 1   Mes Lead       56 non-null     int64
 2   AgLead         56 non-null     str
 3   Titulo         56 non-null     str
 4   Nombre         56 non-null     str
 5   Producto       56 non-null     str
 6   Temperatura    56 non-null     str
 7   Comentario     56 non-null     str
 8   Asesor         56 non-null     str
 9   Fuente         56 non-null     str
 10  Origen         56 non-null     str
 11  Estatus        56 non-null     str
dtypes: datetime64[us](1), int64(1), str(10)
memory usage: 5.4 KB

**Convertir DataSet sin valores nulos a CSV**

In [18]:
#Convertir DataFrame a CSV
data2.to_csv("Base_de_Tlaxcala_Sin_Nulos.csv", index=False)

In [ ]:
#descargar archivo filtrado en csv
#from google.colab import files 
  
  
#files.download("inmuebles_sin_nulos.csv")